[[main]]
  identifier = "programa"
  name = "Programa"
  url = "programa"
  weight = 1
  
[[main]]
  identifier = "Atividades Semanais"
  name = "Atividades Semanais"
  url = "semanal"
  weight = 2

[[main]]
  identifier = "noticias"
  name = "Not√≠cias"
  url = "noticias"
  weight = 5

[[main]]
  identifier = "contato"
  name = "Contato"
  url = "contato"
  weight = 4